name: Chrome Addon Upload

on:
  push:
    branches:
      - master

jobs:
  upload-addon:
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup
        uses: actions/setup-node@v2
        with:
          node-version: "12"

      - name: Dependencies
        run: npm install

      - name: Test
        run: npm run test
      
      - name: Build
        run: npm run build

      - name: Zip
        run: zip -qq -r prod.zip ./dist/prod

      - name: Upload
        uses: trmcnvn/chrome-addon@v2
        with:
          extension: ooinoebmmhbmhkocojcoahbkefikddch
          zip: prod.zip
          client-id: ${{ secrets.CHROME_CLIENT_ID }}
          client-secret: ${{ secrets.CHROME_CLIENT_SECRET }}
          refresh-token: ${{ secrets.CHROME_REFRESH_TOKEN }}
