name: Chrome Addon Upload

on:
  push:
    branches:
      - master

jobs:
  checkout:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v1
      
  setup:
    needs: checkout
    steps:
      - uses: actions/setup-node@v1
        with:
          node-version: "10.x"
      - run: npm install

  test:
    needs: setup
    steps:
      - run: npm run test

  build:
    needs: setup
    steps:
      - run: npm run build
      - uses: montudor/action-zip@v0.1.0
        with:
          args: zip -qq -r ./prod.zip ./dist/prod

  upload:
    needs: [test, build]
    steps: 
      - uses: trmcnvn/chrome-addon@v1
        with:
          extension: ooinoebmmhbmhkocojcoahbkefikddch
          zip: prod.zip
          client-id: ${{ secrets.CHROME_CLIENT_ID }}
          client-secret: ${{ secrets.CHROME_CLIENT_SECRET }}
          refresh-token: ${{ secrets.CHROME_REFRESH_TOKEN }}
